[project]
name = "song-player"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "ipykernel>=7.1.0",
    "pygame>=2.6.1",
    "pyqt6>=6.10.1",
    "uvicorn>=0.40.0",
]
